### ISSUE TITLE
Deleting recipes

### ISSUE THREAD

**Issue by Vyrgax** [mcgrizzz/ProRecipes#16] opened 2018-05-15 15:53 UTC
Whenever I try to delete a recipe, this appears in the console:
https://hastebin.com/sifuxanabo.bash

I consider this as a huge (but also the only) problem with the plugin, since the only other way is entirely deleting the plugin, reupload it, and remake all other recipes except the one you wanted to delete, since deleting it in the recipes.yml and restarting the server doesn't seem to work as well.

This is obviously the best plugin of its kind, so it would be sad seeing this plugin being pulled down by this issue.

**Comment by Vyrgax** [comment] 2018-05-15 15:55
UPDATE: 
The console error appears after clicking on the glowstone block 'Accept' after removing all necessary items needed to craft it

**Comment by mcgrizzz** [comment] 2018-06-05 17:11
Empty code snippet and duplicate of another issue #9

**Closed by mcgrizzz** 2018-06-05 17:11 UTC
